---
title: "Hypothesis testing: additional considerations (Notes)"
subtitle: "STAT 155"
author: "Your Name"
format:
  html:
    toc: true
    toc-depth: 2
    embed-resources: true
---


```{r setup}
#| include: false
knitr::opts_chunk$set(
  collapse = TRUE, 
  warning = FALSE,
  message = FALSE,
  error = TRUE,
  fig.height = 2.75, 
  fig.width = 4.25,
  fig.env = 'figure',
  fig.pos = 'h',
  fig.align = 'center')
```


# Notes

- No template file today - all exercises can be viewed from the webpage

## Learning goals

By the end of this lesson, you should be able to:

- Differentiate between more and less accurate interpretations of p-values
- Explain how different factors affect statistical power
- Explain the difference between practical and statistical significance
- Explain how multiple testing impacts the conduct and interpretation of statistical research

## Readings and videos

No new readings or videos for today.




# Exercises

## Exercise 1: Conceptual understanding

a. Suppose that you and a friend are in two different sections (each with the same number of students) of the same class. On your respective midterm exams, you each obtained 85%, and the class average in both of your classes was 80%. Could one of you or your friend still be considered further above the class average than the other? Briefly explain.

b. Now suppose that your section's test scores were more tightly packed around 80%: maybe the standard deviation of your section's scores was 2.5, whereas the standard deviation of your friend's section's scores was 5. Which of you or your friend was further above the class average? Explain/justify your answer.

c. Broadly speaking, does a p-value measure the chance of a hypothesis being true, or, the chance of the data having occurred?

d. Why can't a p-value measure the other quantity that you didn't choose in Part c?

e. Explain in words why, in calculating a p-value, we need to assume that the null hypothesis is true.

f. Suppose that a hypothesis test yields a p-value of 1e-6 ($1\times 10^{-6}$). What can you tell about the magnitude of the effect or the uncertainty of the effect from this p-value? (i.e., What can you tell about the coefficient estimate or the standard error?)



## Exercise 2: Statistical vs. practical significance

Music researchers compiled information on 16,216 Spotify songs. They looked at the relationship between a song's genre (latin vs. not latin) and song duration in seconds. Their modeling code and output is below:

```r
spotify_model <- lm(duration ~ latin_genre, data = spotify)
coef(summary(spotify_model))
```

```
##                   Estimate Std. Error   t value   Pr(>|t|)
## (Intercept)     212.673908  0.4165491 510.56143 0.00000000
## latin_genreTRUE   1.555355  0.7435700   2.09174 0.03647731
```

a. Interpret the `latin_genreTRUE` coefficient.
b. In the context of song listening, is this a large or small effect size?
c. Report and interpret the p-value for the `latin_genreTRUE` coefficient.
d. Use the p-value to make a yes/no decision about the evidence for a relationship between genre and song duration.
e. This exercise highlights the difference between statistical significance and practical significance---explain how. That is, when might we observe statistically significant results that aren't practically significant?



## Exercise 3: Power

Statistical power is the probability of rejecting the null hypothesis when the alternative hypothesis is true. We are frequently testing hypotheses to investigate differences or relationships, so in this context, statistical power is the probability of detecting a relationship when there truly is a relationship.

Navigate to [this page](https://rpsychologist.com/d3/nhst/) to look at an interactive visualization of the factors that influence statistical power.

Under "Settings", next to the "Solve for?" text, click "Power". You will vary the 3 different parameters (significance level, sample size, and effect size) one at a time to understand how these factors affect power.

Some context behind this interactive visualization:

- Visualization is based on a one sample Z-test:    
    This is a test for whether the true population mean equals a particular value. (e.g., true mean = 30)
- The effect size slider is measured with a metric called Cohen's d:
    - Cohen's d = magnitude of effect/standard deviation of response variable
    - Here: how far is the true mean from the null value in units of SD?
    - e.g., If the null value is 30, true mean is 40, and the true population SD of the quantity is 5, the Cohen’s d effect size is (40-30)/5 = 2.

a. What is your intuition about how changing the significance level will change power? Check your intuition with the visualization and explain why this happens.
b. Repeat Part a for the sample size.
c. Repeat Part a for the effect size.



## Exercise 4: Ethical considerations

a. Visit [this page](https://mchankins.wordpress.com/2013/04/21/still-not-significant-2/) and look at both the comic at the top and the various ways in which researchers have described p-values that do not fall below the $\alpha = 0.05$ significance level threshold. What ethical consideration is arising here? (Just for fun: a related [xkcd comic](https://xkcd.com/1478/))

b. Take a look at the xkcd comic [here](https://xkcd.com/882/). What ethical consideration is arising here?






## Done!

- Finalize your notes: (1) Render your notes to an HTML file; (2) Inspect this HTML in your Viewer -- check that your work translated correctly; and (3) Outside RStudio, navigate to your 'Activities' subfolder within your 'STAT155' folder and locate the HTML file -- you can open it again in your browser.
- Clean up your RStudio session: End the rendering process by clicking the 'Stop' button in the 'Background Jobs' pane.
- Check the solutions in the course website, at the bottom of the corresponding chapter.
- Work on homework!


